plugins: Fix compilation error on autopair
Fix this error caught using gcc 4.6.3:

plugins/autopair.c: In function ‘autopair_init’:
plugins/autopair.c:154:8: error: ignoring return value of ‘fread’,
declared with attribute warn_unused_result [-Werror=unused-result]